FROM debian:bookworm-slim AS lua52_build_base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install lua5.2 liblua5.2-dev luarocks \
           libssl-dev git build-essential m4 \
           ca-certificates \
           --no-install-recommends -y \
    && rm -rf /var/lib/apt/lists/*

RUN luarocks install http \
    && luarocks install luafilesystem

WORKDIR /workspace
COPY .  /workspace
RUN make build.make/lhsrv.tar.gz \
    LUA_INCDIR=/usr/include/lua5.2/ LUA_LIBDIR=/usr/lib/aarch64-linux-gnu/ \
    LUAC=luac5.2 LUA_LIBNAME=lua5.2

##

FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install liblua5.2-0 libc6 ca-certificates \
           --no-install-recommends -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=lua52_build_base \
    /workspace/docker/docker-entrypoint.sh \
    /workspace/build.make/lhsrv.tar.gz   \
    /

COPY --from=lua52_build_base \
    /workspace/docker/docker-entrypoint.d  \
    /docker-entrypoint.d

RUN chmod +x /docker-entrypoint.sh && chmod -R +x /docker-entrypoint.d \
    && tar -xzvf /lhsrv.tar.gz -C /opt \
    && chmod -R +x /opt/lhsrv \
    && ln -sf /opt/lhsrv /usr/bin/lhsrv \
    && rm -rf /lhsrv.tar.gz \
    && chown -R www-data:www-data /srv

ENV LUA_HTTP_SERVER_HOME_DIR=/opt

WORKDIR /srv
USER www-data

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGINT

CMD ["lhsrv", "-h", "0.0.0.0", "-p", "80"]